### ISSUE TITLE
list index out of rannge

### ISSUE THREAD

**Issue by jmutnick** [bramkragten/weather-card#10]
Error:
ERROR (MainThread) [custom_components.weatheralerts.sensor] list index out of range

Frequency: Every 30 seconds

Weather Card: v1.3.2
HA: 0.96.2
Python: 3.7.0

**Comment by jmutnick** [comment]
Seems to have gone away on restart.

**Comment by bramkragten** [comment]
That error is not from this card but from the custom component `weatheralerts`
