### ISSUE TITLE
ClimaCell Nowcast

### ISSUE THREAD

**Issue by jds11111** [bramkragten/weather-card#104]
First off, this is a great card, and I use it for all my forecasts (NWS, MET, OpenWeatherMap). There is now a hyperlocal, every-five-minutes forecast from the ClimaCell integration (yay!). This works really well with your card, except for one thing. If you click on the forecast, it treats it like a daily forecast, and shows just the date, like below. Is there a way to fix this? 
Thanks again for a great card.

![image](https://user-images.githubusercontent.com/15203860/118150014-ba4ed080-b3d7-11eb-91ea-77c995dd1b81.png)

**Comment by bramkragten** [comment]
This has nothing to do with this card, it is just the core HA more info dialog.

**Comment by jds11111** [comment]
Thanks!
