### ISSUE TITLE
Is this repo active?

### ISSUE THREAD

**Issue by martindybal** [bramkragten/weather-card#107]
Hi there is a lot of open issue and also pull request? Is it still active? I want to make a fix but I don't want to create pull request to dead repo.

**Comment by bramkragten** [comment]
It is not actively developed no, but it is maintained.

**Comment by Sudo-Rob** [comment]
Has the weather card been tested with respect to the upgrade to Lit 2.0 in 2021.6?

**Comment by bramkragten** [comment]
Yes

**Comment by Sudo-Rob** [comment]
Thanks for the timely reply.
