### ISSUE TITLE
Card invisible when setting current: true

### ISSUE THREAD

**Issue by podkilla** [bramkragten/weather-card#12]
I have a strange behavior. When i set 'current' to 'true' the card becomes invisible in my lovelace view.
Any idea what might be the reason for this?

My HA version: 0.99.2

Card invisible:
```
type: 'custom:weather-card'
entity: weather.weatherentity
icons: /community_plugin/weather-card/icons/
name: <location>
current: true
details: true
forecast: true
```

Card works as intended (i guess):
```
type: 'custom:weather-card'
entity: weather.weatherentity
icons: /community_plugin/weather-card/icons/
name: <location>
current: false
details: true
forecast: true
```

**Comment by dariolob** [comment]
+1 on this, same here with latest hassio release.

**Comment by bramkragten** [comment]
Anything in the console?

**Comment by timdonovanuk** [comment]
weather-card.js:156 Uncaught (in promise) TypeError: Cannot read property 'state' of undefined
    at HTMLElement.renderCurrent (weather-card.js:156)
    at HTMLElement.render (weather-card.js:138)
    at HTMLElement.update (lit-element.js:163)
    at HTMLElement.performUpdate (updating-element.js:508)
    at HTMLElement._enqueueUpdate (updating-element.js:460)

**Comment by HeaNimi** [comment]
check if you have `sun:` component enabled in your configuration.yaml

**Comment by podkilla** [comment]
> check if you have `sun:` component enabled in your configuration.yaml

thats the issue, activated the sun component and the card is working as intended now
