### ISSUE TITLE
Pixelated Icon

### ISSUE THREAD

**Issue by myevit** [bramkragten/weather-card#121]
On mobile HA ios app main icon get pixelated when forecast icons are on the screen
![IMG_2541](https://user-images.githubusercontent.com/13375246/141723461-431ce17b-f873-4ad3-99f8-77381f0bd11d.jpeg)
.
![IMG_2540](https://user-images.githubusercontent.com/13375246/141723469-4cb24966-92f1-45eb-9480-e53af8736bb0.jpeg)

**Comment by ericmai624** [comment]
Having the same issue on ios. 

On my MBP Chrome it renders fine, but not on ios app.

**Comment by myevit** [comment]
That’s Safari issue.

**Comment by ericmai624** [comment]
> That’s Safari issue.

The default Lovelace weather card is using Svg as well and they look fine in iOS.

**Comment by kimme1024** [comment]
Same issue here... Any idea when this will be fixed in an update?

**Comment by MetroAffe** [comment]
Its crazy. Its only pixelated while focusing

https://user-images.githubusercontent.com/61084462/161273980-eaed2877-b82b-4a39-8937-04c8af921c85.MOV

**Comment by leotantantan** [comment]
Same issue here. Any solutions so far ?
