### ISSUE TITLE
Versions 1.4.7 and 1.5.0 not tagged as releases

### ISSUE THREAD

**Issue by bdr99** [bramkragten/weather-card#132]
Currently, versions 1.4.7 and 1.5.0 are tagged, but not as releases. This causes the latest version to appear as 1.4.6 in HACS, which is a problem because 1.4.6 is broken. As a result, many people are downloading a broken version of the card, not realizing that there is a fixed version (https://github.com/bramkragten/weather-card/issues/127, https://github.com/bramkragten/weather-card/issues/128, https://github.com/bramkragten/weather-card/issues/130). Please tag 1.5.0 as a release so that HACS will automatically download this version without needing to override and choose "master".

![image](https://user-images.githubusercontent.com/2292715/163694148-7c510fad-a0bc-4df3-be64-c6ad8ba50b5a.png)

**Comment by exetico** [comment]
Switched to master. Thanks for the tip. I had the same issues as all the other people.

**Comment by MRxCloud** [comment]
Oh thank you it took me so much time to figure that out!

**Comment by bdr99** [comment]
I see this has been resolved now, so closing this issue.

![image](https://user-images.githubusercontent.com/2292715/180632361-27422c42-ce1d-4702-b87f-c427c9ace2cd.png)
