### ISSUE TITLE
[BUG] Card doesn't support new weather entitles without forecast attributes 

### ISSUE THREAD

**Issue by Scoop2389** [bramkragten/weather-card#159]
**Release with the issue:**
Home Assistant Core: 2023.9

**Last working release:**
Home Assistant Core: 2023.8.4

**Browser and Operating System:**
Windows, Edge, Chrome + Android, Home Assistant Mobile App

**Description of problem:**
In Home Assistant Core 2023.9, a new weather forecast scheme was introduced in which entities no longer have forecast attributes, and instead forecast data must be retrieved by calling a service (weather.get_forecast) ([Ref](https://www.home-assistant.io/blog/2023/09/06/release-20239/#weather-forecast-service)). This card does not call the service, and therefore entities without forecast attributes do not show the forecast in this card. Weather entities with forecast attributes are now depreciated and will be removed in core version 2024.3.

**Comment by Lotharion94** [comment]
The last update of the branch of weather-card have be done from 2 years ago.

**Comment by bramkragten** [comment]
https://github.com/bramkragten/weather-card/commit/b665f6cab338073ae3ced3948e21001553794430
