### ISSUE TITLE
Support for hourly forecast would be nice

### ISSUE THREAD

**Issue by mback2k** [bramkragten/weather-card#20]
Since the Dark Sky weather integration supports `hourly` mode, it would be nice to support that by showing the hour instead of the same day abbreviation for the 5 columns.

**Comment by valantur** [comment]
100% baby!

**Comment by bobzer** [comment]
you can try my repo I did exactly that 
https://github.com/bobzer/weather-card

**Comment by Luc3as** [comment]
Hi, I also created PR to implement this  #45

**Comment by vbtrek** [comment]
Brilliant, I was just looking for this functionality, looking forward to it getting released on HACS.
