### ISSUE TITLE
weather card to esp8266 with LCD 3.2"

### ISSUE THREAD

**Issue by wisesokol** [bramkragten/weather-card#21]
HI. In home assistant your card works very well. 
I would like to show the weather on a separate screen (ESP8266 with LSD 3.2") , at the exit from the house.
Project (https://www.youtube.com/watch?v=ImEp7kB_nrs) (https://learn.adafruit.com/wifi-weather-station-with-tft-display/software). I do not like. Bad design. It would be nice to have one style with the HOme assistant.

**Comment by bramkragten** [comment]
That is not using a web interface, so it is not possible to use this card.
