### ISSUE TITLE
⚠️ Information: Future card configuration changes.

### ISSUE THREAD

**Issue by thomasloven** [bramkragten/weather-card#26]
Hi.

A change in how lovelace cards are set up in Home Assistant 0.105 increases performance, but enables cards to accidentally modify their own configuration in the loaded lovelace configuration.

I'm going through the cards in the HACS default repository, and noticed that your card may be susceptible to this. Looking through your code it seems you may modify parts of the config object passed to your card in `setConfig`.

The result could be that your card does not work well with the GUI editors or that parts of the configuration start showing up multiple times.

At some point in the future, it is likely that the configuration will be frozen before being passed to `setConfig`. At this point, your card will fail entirely when it tries to modify the configuration object.

There are several ways to fix/protect agains this problem.

The best is to restructure `setConfig` such that the configuration is never modified.
Other alternatives are to make a copy of the configuration and work on that instead.

```javascript
setConfig(config) {
  config = { ...config }; // This works for simple configurations not containing arrays or objects
...
```
```javascript
import { deepClone } from "deep-clone-simple";
// https://github.com/balloob/deep-clone-simple

setConfig(config) {
  config = deepClone(config); // This is a safe and fast method
...
```
or
```javascript
setConfig(config) {
  config = JSON.parse(JSON.stringify(config)); // This uses built-in functions, but may be slower than deepClone
  ...
```

Please note that I have not tested your card agains Home Assistant 0.105 or later, but just quickly looked through the code. If I'm mistaken in my assessment, I appologize for taking your time.

See thomasloven/hass-config#6 for more info.

Special note, because it's you: It's in the editor. Right before writing the configuration back.

**Comment by thomasloven** [comment]
I'm wrong.
The editor should still work even in the future.

**Comment by bobzer** [comment]
Anyway thank you for your time and the warning :+1:
