### ISSUE TITLE
No Animation

### ISSUE THREAD

**Issue by GlennFast** [bramkragten/weather-card#33]
I followed the instruction and i see the weather-card on my lovelace screen.
But i dont see the animated pictures. Any idea what i did wrong. 
All the intern URL are double checked and are correct.

**Comment by thEngal** [comment]
I have the same problem with Safari on MacOS. Try another browser like Google Chrome.

**Comment by P-Verbrugge** [comment]
Same issue here with Safari on MacOS. In other browsers it's animated.

**Comment by Kugelfang666** [comment]
same problem here macOS Catalina and safari

**Comment by rpbx** [comment]
Same issue on IOS companion app

**Comment by Tony112lx** [comment]
No solution for safari browser and iOS app?

**Comment by febalci** [comment]
IOS 13.4 and Safari 13.1 is suffering this issue. Previous versions were working fine...

**Comment by niekniek89** [comment]
Hello,

i upgraded my iPhone to IOS 13.5, and HA to 0.110.1, and for me is the problem solved

**Comment by Tony112lx** [comment]
> Hello,
> 
> i upgraded my iPhone to IOS 13.5, and HA to 0.110.1, and for me is the problem solved

Yes now work well!
