### ISSUE TITLE
Temperature from my own sensor

### ISSUE THREAD

**Issue by trojan-tj** [bramkragten/weather-card#35]
How to change the display of the current temperature to the temperature from my own sensor. I tried to edit the JS-file, but it did not give a positive result

**Comment by benaisn** [comment]
same here :)

**Comment by CMDR-Sloma** [comment]
I'd like to know this as well.

Thank you.

**Comment by bramkragten** [comment]
You would have to this manually in the code, I will not add that to this card. I know there are forks of this card that support that.
