### ISSUE TITLE
switched to Lovelace Dashboards and card is not working anymore

### ISSUE THREAD

**Issue by GitHubxtsnl** [bramkragten/weather-card#40]
running HA 0.107.5
I recently switches to Lovelace Dashboards. I created a copy of an existing .yaml file and associated with the newly created Dashboard. An now I get the error "Custom element doesn't exist: weather-card."

![image](https://user-images.githubusercontent.com/43134674/77314056-3f26e880-6d05-11ea-877a-4b93c94c26c2.png)

`  - type: module
    url: /community_plugin/weather-card/weather-card.js`

This is my .yaml config:

and

`        - type: custom:weather-card
          entity: weather.rp39`

**Comment by bramkragten** [comment]
Resources shouldn't be in the `yaml` file with your Lovelace config but in `configuration.yaml`
<https://www.home-assistant.io/lovelace/yaml-mode/>

**Comment by GitHubxtsnl** [comment]
I moved the resources to the configuration.yaml file and this fixed the issue.
