### ISSUE TITLE
Dark Sky API Ending 2020 - Alternative Integration?

### ISSUE THREAD

**Issue by thehaxxa** [bramkragten/weather-card#42]
As Dark Sky is pulling their API at the end of 2020, I was wondering if this Card worked with any other weather integrations (particularly any international services)?

I tried some from here but none displayed 7 day forecasts:
https://www.home-assistant.io/integrations/#weather

**Comment by bramkragten** [comment]
This card works with every weather platform, I can't advise you on a weather platform for your region.
