### ISSUE TITLE
HIgh CPU

### ISSUE THREAD

**Issue by pepebc** [bramkragten/weather-card#46]
I have tried tests with Firefox, Chromium, Falkon, Opera, Midori, Epiphany ... and in all browsers the CPU remains between 75% and 90%
Isn't it possible to disable animation or make the code lighter?

**Comment by bramkragten** [comment]
There is no heavy code in this card, and the animation is just css, nothing heavy. I don't think the CPU is from this card.

But you can disable the animation by setting the `icons` option to a path with static icons. <https://github.com/bramkragten/weather-card/tree/master/icons/static>

**Comment by jjmonteiro** [comment]
I can confirm this card might cause some CPU stress, probably the way the browser handles the animations.
I've created a test view just for it, and I can hear the CPU fan going up while displaying it and going silent when removed from the UI, and I'm running a Core i7.
Further investigation shows ~20% increase in CPU usage and ~20°C in temperature.
Disabling the animations as suggested by @bramkragten solves the issue, but you need to be running the local script.

![weather_card](https://user-images.githubusercontent.com/31997649/82953354-8a2dd800-9fa2-11ea-977c-4b2a6b315bba.jpg)

**Comment by bramkragten** [comment]
What browser do you use? CSS animations should be very resource-friendly.

**Comment by jjmonteiro** [comment]
oh sorry forgot to mention, Google Chrome, latest release.

**Comment by david-kalbermatten** [comment]
I get similar performance issues with the mobile app when using this integration. Very noticeable on my older Samsung Galaxy Tab A6 (2017).

**Comment by theone11** [comment]
I have just found I have the same issue.

Using rasberry pi (latest OS and Chromium) as touch screen browser (HA runs on different platform).

When the weather card is **enabled** the CPU usage is ~190% and PI core temperature easily reaches 65-70C and rising (with big heatsink):
![image](https://user-images.githubusercontent.com/3348953/86626282-2817b800-bfcf-11ea-9f71-a0f1a45cfd84.png)

When the weather card is **disabled** (nothing else changed) CPU usage is <5% (chromium is showing 0%) and PI core temperature drops to ~50C (very fast):
![image](https://user-images.githubusercontent.com/3348953/86626710-bf7d0b00-bfcf-11ea-906b-17369c712610.png)

**Comment by bramkragten** [comment]
I'm going to close this as not going to fix/upstream issue.
If your device can't handle it, disable the animation.
