### ISSUE TITLE
Card padding reduced in 0.109.1

### ISSUE THREAD

**Issue by thehaxxa** [bramkragten/weather-card#47]
Since upgrading to 0.109.1 the padding around the weather card has gotten small causing the text around the top to almost be cut off:

![image](https://user-images.githubusercontent.com/2765052/80774953-a60bad00-8ba1-11ea-9775-2309a3d7963b.png)

Not sure if cause is weather card or an external factor, but only appeared since upgrading to Home Assistant 0.109.1

**Comment by rgruyters** [comment]
Same here.

**Comment by Shamshala** [comment]
Same for me on two HA machines. :slightly_smiling_face:

**Comment by KrzesloSzatan** [comment]
same here

**Comment by tomhall12345** [comment]
Same here.

**Comment by Shamshala** [comment]
Ok, temporary fix in case of [card-mod](https://github.com/thomasloven/lovelace-card-mod)
```
entity: weather.home
type: 'custom:weather-card'
style:
  .: |
    ha-card div.current span.temp {
      font-size: 4em;
      right: 1em;
      top:0.5em;
     }
```

**Comment by Shamshala** [comment]
Ok, internal me was screaming enough evertime i opened my frontend :rofl:  Temporary fix in case of [card-mod](https://github.com/thomasloven/lovelace-card-mod)
```
entity: weather.home
type: 'custom:weather-card'
style:
  .: |
    ha-card div.current span.temp {
      font-size: 4em;
      right: 1em;
      top:0.5em;
     }
```

**Comment by bramkragten** [comment]
There is an update in the master branch for some time, if somebody wants to test that.

**Comment by Ndrinta** [comment]
Hi Shamshala, many thanks for that!
I think that your css tweak fixes part of it but when it rains the drops are going in the background of the below text.
![image](https://user-images.githubusercontent.com/4704172/83612151-ecc23d80-a579-11ea-8d4f-26493f3e6f4a.png)
I know that the best solution would be just to leave this sad island and go somewhere where "rain" isn't the most likely weather condition but for the moment I'm stuck in UK.
I know that I should just tweak my css to get the result I want but I'm really bad at that and I swear I tried but unfortunately nothing good happened. Can you please help me to identify the parameter I should play with (and possibly how)? Please :)

**Comment by Shamshala** [comment]
Sorry, i haven't noticed your post. Try the latest release, @bramkragten fixed the issues. :slightly_smiling_face:
