### ISSUE TITLE
Local icons are no longer displayed

### ISSUE THREAD

**Issue by bussio** [bramkragten/weather-card#51]
Since HA 0.100.x no local icons (icons:" / local / custom-lovelace / weather-card / icons / ") have been shown in this weather card.

**Comment by bramkragten** [comment]
You don't provide much info, it does work here...

What is your config?

**Comment by P-Verbrugge** [comment]
In my case the update from v1.4.3 to v1.4.4 broke the loading of local icons. 

I run HA version 0.110.4. On verion 1.4.3 the local set with icons is loaded correcly.

This is my lovelace code:
`      - entity: weather.dark_sky
        icons: /local/weather-card/animated_icons/
        type: 'custom:weather-card'
`

**Comment by bussio** [comment]
> What is your config?

This is the code that I've been using for a long time and that has always worked?!

    - type: custom:weather-card 
      style: |
        ha-card {
          --ha-card-background: rgba(255, 255, 255, 0.3);
          border-radius: 15px;  
        }
      entity: weather.openweathermap
      icons: "/community_plugin/weather-card/icons/"
      name: Harrislee

**Comment by bramkragten** [comment]
`community_plugin` is no longer supported by HACS I believe.

**Comment by bussio** [comment]
> `community_plugin` is no longer supported by HACS I believe.

That was it. Thank you very much. The problem is solved.

**Comment by dyfcom** [comment]
Got the same Problem. But with:
`resources:
  - url: /hacsfiles/weather-card/weather-card.js
    type: module`

using openweathermap at the moment.
![grafik](https://user-images.githubusercontent.com/47184285/85927923-79c29300-b8a9-11ea-9c9d-09c5a0ba750b.png)

I reinstalled it and restarted HA.

**Comment by bramkragten** [comment]
What is the config of your card?

**Comment by MolsonB** [comment]
> > `community_plugin` is no longer supported by HACS I believe.
> 
> That was it. Thank you very much. The problem is solved.

What did you do ?
