### ISSUE TITLE
Removed from HA community/HAKS?

### ISSUE THREAD

**Issue by simonlock** [bramkragten/weather-card#54]
Has this been removed from HA community/HAKS? Today this stopped working for me. I tried reinstalling which didn't help. Can this still work in HA or is an update required now?

**Comment by Jacoleroux** [comment]
I'm having the same issue , "not loading"

**Comment by LucaDev** [comment]
Which weather provider are you using? The met.no integration seems to have stopped working. At least for me.

**Comment by VR29** [comment]
C

> Which weather provider are you using? The met.no integration seems to have stopped working. At least for me.

I have the same problem

**Comment by simonlock** [comment]
I've just installed the latest HA update and my weather card is showing again. On startup, it initially complains "Custom element doesn't exist: weather-card." but then shows up correctly. However, It doesn't show up on the iOS app complaining again "Custom element doesn't exist: weather-card.".

**Comment by chokmi** [comment]
Same issues 😕

**Comment by vader9988** [comment]
I have the same problem does not load the card

**Comment by bramkragten** [comment]
Any errors?

**Comment by vader9988** [comment]
does not show the weather data only the empty card appears.

**Comment by bramkragten** [comment]
Still not much info... provide a screenshot, environment info, and the browser console output.

**Comment by chokmi** [comment]
Hi,

In my case, i have this issue

![card](https://user-images.githubusercontent.com/64916455/86170663-c0b7bf00-bb1b-11ea-9e5f-8b3f4b4ef852.PNG)
![card2](https://user-images.githubusercontent.com/64916455/86170665-c1505580-bb1b-11ea-82f5-b59a4a02f887.PNG)
![card3](https://user-images.githubusercontent.com/64916455/86170666-c1e8ec00-bb1b-11ea-8ee0-e24bb8b9aab6.PNG)

**Comment by bramkragten** [comment]
That is not an issue with the card, check your resources.

**Comment by simonlock** [comment]
Just updated homeassistant and now the card is in error again. Just like the screenshot above. This weather card seems to have been removed from HACS/Community, could this be the problem we are facing?

**Comment by Jacoleroux** [comment]
> 
> 
> Just updated homeassistant and now the card is in error again. Just like the screenshot above. This weather card seems to have been removed from HACS/Community, could this be the problem we are facing?

I just updated and mine is still working, you might have to reboot or restart your HA again if not already done.
I had the same issue but after 20min I just refreshed my browser and it was back.

**Comment by schettada** [comment]
Have the same issue with this card. it was working as expected and from today it started with error that the 'custom element doesnt exist'. I didnt make any changes except HA was upgraded to 112.4. Seems like the resource loading location is changed to '/local/community/weather-card/weather-card.js'. Once this location was added to lovelace resource it started working. But HACS still says that the resource is not loaded. 

![Screen Shot 2020-07-10 at 12 01 15 AM](https://user-images.githubusercontent.com/16140432/87121662-7d0e3500-c240-11ea-8952-4981bd6592e2.png)

**Comment by ChrisRomp** [comment]
HACS maps the `config/www/community` path to `/hacsfiles` on the web server.  So add this to your `configuration.yaml`:

```yaml
- url: /hacsfiles/weather-card/weather-card.js
  type: module
```
