### ISSUE TITLE
Round mm value

### ISSUE THREAD

**Issue by frankiha** [bramkragten/weather-card#68]
<img width="242" alt="weather" src="https://user-images.githubusercontent.com/53922329/90552553-6628ff80-e169-11ea-8b31-8a2cf4dadadc.png">

**Comment by ImmortalScientist** [comment]
BLoody awful bugreport @frankiha - it's good practice to give some context; version, etc.

I can confirm I'm having the same issue in v1.4.6 installed through HACS. Home Assistant v0.114.2.

Seems inconsistent - some values are rounding correctly, and some have similar to frankhika's screenshot.

![image](https://user-images.githubusercontent.com/22246611/90707134-cfeef980-e28e-11ea-812b-58d63f41079e.png)

**Comment by DENightOne** [comment]
This issue was closed yesterday.

https://github.com/bramkragten/weather-card/issues/65

You need to manualy copy the code of make the change yourself as this code hasnt been released on HACS yet

**Comment by bramkragten** [comment]
> This issue was closed yesterday.
> 
> #65
> 
> You need to manualy copy the code of make the change yourself as this code hasnt been released on HACS yet

It is, you can use the master branch.
