### ISSUE TITLE
Allow changing current temperature to display value from different sensor

### ISSUE THREAD

**Issue by yuvalabou** [bramkragten/weather-card#71]
The new Accuweather integration exposing a new sensor called sensor.realfeel and I would like to display it instead of the default value from the weather.home

**Comment by thomasgermain** [comment]
Hi,

I actually have the same kind of feature request :)
I have an outdoor temperature sensor and it would be nice to have both (or configurable ?) values displayed in the weather card.

kr,

Thomas

**Comment by tonioa** [comment]
Hi, Same here i would like to integrate my own outdoor temperature sensor 

Thanks

**Comment by jburke26** [comment]
I agree, I have a outdoor weather station and I would like to use my own sensors.

**Comment by CMDR-Sloma** [comment]
I would like to also join in request of these features. I have my own solar-powered weather station with temperature, humidity, air pressure exposed to home assistant. In the future I will add wind speed and wind speed direction with rain accumulation and UV index sensor. 

If you are not planning to add it for any reason I would be grateful if you can just tell me how I can implement it myself by editing the card. 

Thanks for any help, and thanks for even making this card.

**Comment by boybert** [comment]
Check out the [Template Weather Provider](https://www.home-assistant.io/integrations/weather.template/) integration. Allows you to relatively easily combine weather information from various entities (including other weather entities and local sensors) and present them in one weather entity.  This might meed your needs; set up the template weather entity, then present that new entity in the card.

**Comment by CMDR-Sloma** [comment]
Thanks for that tip, I will definitely try this. I was looking for something similar for the past year and it never crossed my mind it is that simple.

**Comment by bramkragten** [comment]
> Check out the [Template Weather Provider](https://www.home-assistant.io/integrations/weather.template/) integration. Allows you to relatively easily combine weather information from various entities (including other weather entities and local sensors) and present them in one weather entity. This might meed your needs; set up the template weather entity, then present that new entity in the card.

This is indeed the correct answer. I will not add this functionality to this card.

**Comment by boybert** [comment]
> Thanks for that tip, I will definitely try this. I was looking for something similar for the past year and it never crossed my mind it is that simple.

Looks like this integration was only released in March of this year, so I guess you and others were ahead of your time :)
