### ISSUE TITLE
Card broken in 0.116.0b0

### ISSUE THREAD

**Issue by VDRainer** [bramkragten/weather-card#75]
Simply doesn't show up.
Console doesn't say much.
![Auswahl_401](https://user-images.githubusercontent.com/26381449/94811128-40904680-03f5-11eb-924c-8728cd7db035.png)

**Comment by tigattack** [comment]
Can confirm., same for me.   
You can see there's a slight gap where it should be, below the top card: 
![image](https://user-images.githubusercontent.com/10629864/94858827-88ca5b80-042b-11eb-88c9-4c21f28a4c46.png)

Code editor confirms correct config: 
![image](https://user-images.githubusercontent.com/10629864/94858933-adbece80-042b-11eb-8e64-f8c241c15aa3.png)

**Comment by armanpermadi** [comment]
yes, im having the same problems too...
using latest update (0.116.0b1) still the same.

**Comment by bramkragten** [comment]
Yeah, I'm aware of the issue. I'll fix it tonight.

**Comment by armanpermadi** [comment]
> Yeah, I'm aware of the issue. I'll fix it tonight.

problem solved... thank you...
