### ISSUE TITLE
Please add option to hide precipitation 

### ISSUE THREAD

**Issue by fillwe** [bramkragten/weather-card#8]
Hello!

Nice addition with the precipitation in the latest release! Would really like an config option to hide that though! Really great card, thanks for the hard work!

**Comment by bramkragten** [comment]
Thanks. I will look into it.

**Comment by tottka** [comment]
I like the addition but have little need for it.  I have a 4 column display where space is limited.  The precipitation line is taking up 2 lines.  1 for the icon & value and 1 line for in(ch).  Could you change the abbreviation from in to double quotes?  Hopefully that will eliminate the second line.

Thank You for all the hard work that goes into this card.

**Comment by TorqueDelight** [comment]
It will still do this using "mm" as unit.

I suggest to remove the rainy cloud icon so it's uniform with the other values.
If there's a rain forecast, the animated icon will show it.

**Comment by bramkragten** [comment]
Added a `hide_precipitation` option and removed the icon in v1.3.2
