### ISSUE TITLE
Custom element doesn't exist: custom:weather-card

### ISSUE THREAD

**Issue by P-Verbrugge** [bramkragten/weather-card#9]
As soon as I upgrade using HACS from version 1.2.1 to version 1.3.0 I get the error: custom:weather-card. I have nothing special in card.

`entity: weather.dark_sky
icons: /community_plugin/weather-card/icons/
type: 'custom:weather-card'`

As soon as I downgrade it works again.

**Comment by bramkragten** [comment]
Please provide some information:

- What browser do you use?
- Does it work in a different browser?
- Are there any errors in the console?

**Comment by P-Verbrugge** [comment]
I use Safari on a Mac. I noticed just now it works in Chrome on the Mac.

The console gives these JS errors:
`
[Error] SyntaxError: Unexpected token '='. Expected an opening '(' before a method's parameter list.
[Error] Unhandled Promise Rejection: /community_plugin/weather-card/weather-card.js
	(anonieme functie)
	rejectPromise`

**Comment by bramkragten** [comment]
This should be fixed in v1.3.1

**Comment by Maikl3** [comment]
Some problem.

Custom element doesn't exist: weather-card.
{
  "type": "custom:weather-card",
  "entity": "weather.dark_sky",
  "name": "weather"
}

i'm using HASS.io 0.98.1
hacs  0.13.2
weather card plugin 1.3.2

according to instructions
In RAW config add 
- url: /community_plugin/weather-card/weather-card.js
    type: module

 browser maxthon. But google chrome is the same.

**Comment by bramkragten** [comment]
Logs?

**Comment by Maikl3** [comment]
I found only the log of Home assistent itself. If you need more, tell me where to look.

http://192.168.1.36:8123/community_plugin/weather-card/weather-card.js:1:11 Uncaught SyntaxError: Unexpected token import
